# Chinese names for every menu item, keyed by the cleaned English name.
# Where the restaurant's own GBP photos (gbp-photo/) name a dish, that name is used verbatim.
CN_NAMES = {
    # Appetizer
    'Crab Rangoon (6)': '蟹角',
    'Egg Roll (1)': '春卷',
    'Scallion Pancake': '葱油饼',
    'Edamame': '毛豆',
    'Fried Shrimp (6)': '炸虾',
    # Small Eats
    'Chili Oil Pork Dumplings (8)': '钟水饺',
    'Boiled Pork Dumpling (8)': '水饺',
    'Sichuan Spicy Pork Wonton (8)': '红油抄手',
    'Pork Wontons In Clear Broth (8)': '清汤抄手',
    'Soup Pork Dumplings (7)': '小笼包',
    'Pan-Fried Pork Dumpling (8)': '煎饺',
    # Cold Dish
    'Spicy Beef & Tripe In Chili Oil': '夫妻肺片',
    'Eggplant w. Sichuan Pepper Sauce': '擂椒茄子',
    'Preserved Egg w. Spicy Pepper': '尖椒皮蛋',
    'Sliced Pork Belly w. Garlic Sauce': '蒜泥白肉',
    'Smashed Cucumber Salad': '拍黄瓜',
    'Sichuan-Style Liangfen': '凉粉',
    # Soup
    'Seafood Soup': '海鲜羹',
    'West Lake Beef Soup': '西湖牛肉羹',
    'Wonton Soup': '馄饨汤',
    'Egg Drop Soup': '蛋花汤',
    'Hot & Sour Soup': '酸辣汤',
    # Noodles/Rice
    'Beef Noodle Soup': '牛肉汤面',
    'Seafood Noodle Soup': '海鲜汤面',
    'Sichuan Style Braised Beef Noodle Soup': '红烧牛肉面',
    'Spicy & Sour Rice Noodles': '酸辣粉',
    'Signature Chow Mein': '招牌炒面',
    'Vegetable Chow Mein': '素炒面',
    'Signature Fried Rice': '招牌炒饭',
    'Vegetable Fried Rice': '素炒饭',
    'Signature Stir-Fried Rice Noodles': '招牌炒米粉',
    'Vegetable Stir-Fried Rice Noodles': '素炒米粉',
    'Seafood Pineapple Fried Rice': '海鲜菠萝炒饭',
    'Stir-Fried Wide Rice Noodles': '干炒牛河',
    'Dan Dan Noodles': '担担面',
    # Beef
    'Beef w. Bean Curd': '豆花牛',
    'Spicy Boiled Beef': '水煮牛',
    'Kung Pao Beef': '宫保牛',
    'Beef Broccoli': '芥兰牛',
    'Beef In Garlic Sauce': '鱼香牛',
    'Pepper Steak': '青椒牛',
    'Mushroom Beef': '蘑菇牛',
    'Hunan Beef': '湖南牛',
    'Cumin Beef': '孜然牛',
    'Mongolian Beef': '蒙古牛',
    'Hunan-Style Stir-Fried Beef': '小炒黄牛肉',
    'Spicy Diced Beef': '辣子牛肉',
    'Stir-fried Beef w. Scallions': '葱爆牛',
    # Lamb
    'Stir-Fried Lamb w. Scallion': '葱爆羊',
    'Dry Pot Lamb': '干锅羊肉',
    'Cumin Lamb': '孜然羊',
    # Chicken
    "General Tso's Chicken": '左宗鸡',
    'Sweet & Sour Chicken': '甜酸鸡',
    'Chicken w. Cashew Nut': '腰果鸡',
    'Chicken Broccoli': '芥兰鸡',
    'Orange Chicken': '陈皮鸡',
    'Hunan Chicken': '湖南鸡',
    'Green Bean Chicken': '四季豆鸡',
    'Kung Pao Chicken': '宫保鸡',
    'Sesame Chicken': '芝麻鸡',
    'Cumin Chicken': '孜然鸡',
    'Mushroom Chicken': '蘑菇鸡',
    'Chicken In Garlic Sauce': '鱼香鸡',
    'Chongqing Spicy Chicken': '辣子鸡',
    # Duck
    'Sichuan-Style Poached & Roasted Duck': '冒烤鸭',
    'Half Peking Duck': '北京烤鸭（半只）',
    'Whole Peking Duck': '北京烤鸭（整只）',
    'Dry Pot Beer Duck': '啤酒鸭',
    'Dry Pot Duck Head': '干锅鸭头',
    # Pork
    'Hunan-Style Stir-Fried Pork': '小炒肉',
    'Hunan-Style Stir-Fried Bamboo Shoot': '小炒笋',
    'Salt & Pepper Pork Ribs': '椒盐排骨',
    'Spicy Pork Ribs': '香辣排骨',
    'Sweet & Sour Pork Ribs': '糖醋排骨',
    "Mao's Braised Pork": '红烧肉',
    'Spicy Noodles w. Minced Meat': '蚂蚁上树',
    'Shredded Pork w. Sweet Bean Sauce': '京酱肉丝',
    'Pork Intestines w. Bean Curd': '豆花肥肠',
    'Stir-Fried Pork Kidney': '火爆腰花',
    'Shredded Pork w. Garlic Sauce': '鱼香肉丝',
    'Dried Tofu & Shredded Pork': '香干肉丝',
    'Pickled Pork Tripe': '酸菜猪肚',
    'Pickled Pepper Pork Tripe': '泡椒猪肚',
    # Cured Meats
    'Bamboo w. Cured Meat': '腊味炒笋',
    'Stir-Fried Cured Meat w. Green Bell Pepper': '青椒炒腊肉',
    'Sautéed Cauliflower w. Cured Meat': '腊肉炒花菜',
    # Tofu
    'Stir-Fried Dried Tofu': '小炒香干',
    'Mapo Tofu': '麻婆豆腐',
    'Dry Pot Shredded Tofu': '千叶豆腐',
    "General Tso's Tofu": '左宗豆腐',
    'Salt & Pepper Tofu': '椒盐豆腐',
    'Sesame Tofu': '芝麻豆腐',
    'Dry Spicy Crispy Tofu': '香辣脆皮豆腐',
    'Kung Pao Tofu': '宫保豆腐',
    # Vegetable
    'Dry Pot Cauliflower': '干锅花菜',
    'Dry Pot Shredded Cabbage': '手撕包菜',
    'Eggplant In Garlic Sauce': '鱼香茄子',
    'Dry-Fried Green Beans': '干煸四季豆',
    'Hot & Sour Shredded Potatoes': '酸辣土豆丝',
    'Sautéed Potato, Eggplant & Green Beans': '地三鲜',
    'Stir-Fried Bok Choy w. Shiitake Mushrooms': '冬菇菜心',
    'Stir-Fried Egg & Tomato': '番茄炒蛋',
    'Chinese Broccoli In Oyster Sauce': '蚝油芥兰',
    'Stir-Fried Pea Shoots w. Garlic': '蒜蓉豆苗',
    'Stir-Fried Water Spinach w. Garlic': '蒜蓉空心菜',
    # Chef Special
    'Spicy Grilled Live Fish': '香辣烤活鱼',
    'Garlic Grilled Live Fish': '蒜香烤活鱼',
    'Pickled Pepper Grilled Live Fish': '泡椒烤活鱼',
    'Mala Grilled Live Fish': '麻辣烤活鱼',
    'Tomato Grilled Live Fish': '番茄烤活鱼',
    'Griddle Fish Fillet': '干锅脆鱼',
    'Spicy Blood Curd & Tripe Stew': '毛血旺',
    'Braised Pork w. Preserved Vegetable': '梅菜扣肉',
    'Twice-Cooked Pork': '回锅肉',
    'Sour Soup Beef': '酸汤肥牛',
    'Pickled Pepper Fresh Frog (Large)': '泡椒田鸡（大）',
    'Cumin Lamb (Chef Special)': '孜然羊',
    'Fried Shrimp w. Salt & Pepper': '椒盐虾',
    'Green Pepper Spicy Fish': '青椒鱼',
    "Xiaoxiang Pig's Feet": '小炒猪蹄',
    'Dry Fried Pork Intestines': '干煸肥肠',
    # Dry Hot Pot
    'Spicy Squid Dry Hot Pot': '香锅鱿鱼',
    'Spicy Pork Intestine Dry Hot Pot': '香锅肥肠',
    'Spicy Sliced Beef Dry Hot Pot': '香锅牛肉',
    'Spicy Frog Dry Hot Pot': '香锅田鸡',
    'Spicy Combination Dry Hot Pot': '麻辣香锅组合',
    # Seafood
    'Fish Fillet w. Pickled Mustard Greens': '酸菜鱼片',
    'Sweet & Sour Fish Fillet': '糖醋鱼片',
    'Fish Fillet w. Bean Curd': '豆花鱼片',
    'Salt & Pepper Fish Fillet': '椒盐鱼片',
    'Boiled Fish Fillet': '水煮鱼片',
    'Spicy Fish Fillet': '香辣鱼片',
    'Fish Fillet In Hot Chili Oil': '沸腾鱼片',
    'Sesame Shrimp': '芝麻虾',
    "General Tso's Shrimp": '左宗虾',
    'Orange Shrimp': '陈皮虾',
    'Walnut Shrimp': '核桃虾',
    'Stir-Fried Shell-Less Shrimp': '炒虾仁',
    'Spicy Shrimp': '香辣虾',
    'Frog w. Chili Sauce (Large)': '馋嘴田鸡（大）',
    'Frog w. Pickled Peppers (Large)': '泡椒田鸡（大）',
    'Cumin Squid': '孜然鱿鱼',
    'Salt & Pepper Squid': '椒盐鱿鱼',
    # Snakehead Fish Fillets
    'Sichuan Peppercorn Snakehead Fish Slices': '藤椒黑鱼片',
    'Pickled Mustard Greens Snakehead Fish Slices': '酸菜黑鱼片',
    'Boiled Snakehead Fish Slices': '水煮黑鱼片',
    'Hot Chili Oil Snakehead Fish Slices': '沸腾黑鱼片',
    # Live Fish
    'Dry-Fried Fish': '干烧鱼',
    'Spicy Szechuan Peppercorn Fish': '麻麻鱼',
    'Fish w. Pickled Mustard Greens': '酸菜鱼',
    'Spicy Grilled Fish': '香辣烤鱼',
    'Mala Grilled Fish': '麻辣烤鱼',
    'Garlic Sauce Grilled Fish': '蒜香烤鱼',
    'Paper-Wrapped Fish': '纸包鱼',
    'Fish In Hot Chili Oil': '沸腾鱼',
    'Fish w. Spicy Bean Sauce': '豆瓣鱼',
    # Side Order
    'White Rice': '白米饭',
    'Hot Chili Oil': '红油',
    # Dessert
    'Brown Sugar Glutinous Rice Cake (6)': '红糖糍粑',
    'Chengdu Ice Powder': '冰粉',
    'Sesame Balls (8)': '芝麻球',
    'Sweet Rice Balls In Rice Wine Soup': '酒酿丸子',
    # Beverages
    'Coke': '可乐',
    'Diet Coke': '健怡可乐',
    'Dr. Pepper': '胡椒博士',
    'Sprite': '雪碧',
    'Bottle Water': '瓶装水',
    'Yeos Soymilk': '杨协成豆奶',
    'Red Bull': '红牛',
    'Can Sodas': '罐装汽水',
    'Sour Plum Drink': '酸梅汤',
    'Green Tea': '绿茶',
    'Jasmine Tea': '茉莉花茶',
    'Hot Tea': '热茶',
    'Lemonade': '柠檬水',
    'Wang Lao Ji': '王老吉',
    'Coconut Milk': '椰奶',
    'Orange Soda': '橙味汽水',
    'Unsweet Tea': '无糖冰茶',
}
